### ISSUE TITLE
Doubled paragraph in "Blocks & Canvas" section

### ISSUE THREAD

**Issue by banDeveloper** [anytypeio/docs#10]
#### Link
[Blocks & Canvas](https://doc.anytype.io/d/fundamentals/object/blocks-and-canvas)

#### Description
Doubled paragraph.
> You can add any information you like by hitting the + button or in-line by typing /. Highlight a block to see its size or move it elsewhere on the canvas. To create a column, drag one block to the end of another block.

Followed by;

> Add any information you like by hitting the + button or in-line by typing /. Highlight a block to see its size or move it elsewhere on the canvas. To create a column, drag one block to the end of another block.

**Comment by div3xi** [comment]
corrected, thank you @banDeveloper.
