### ISSUE TITLE
“Blog” in top navigation links to Github, not blog

### ISSUE THREAD

**Issue by LukasMurdock** [anytypeio/docs#11]
#### Link
Correction is located in top navigation link, so all pages

#### Description
The “Blog” link in the top-navigation of the [Anytype documentation](https://doc.anytype.io/d/) currently links to [https://github.com/anytypeio](https://github.com/anytypeio) instead of [https://www.anytype.blog/](https://www.anytype.blog/)

<img width="854" alt="Screen Shot 2022-03-26 at 5 20 36 PM" src="https://user-images.githubusercontent.com/3117665/160257581-f5828425-d6e3-4bd0-892a-144b5f840068.png">

```html
<a
  href="https://github.com/anytypeio"
  dir="auto"
  aria-label="Blog"
  data-rnw-int-class="nearest___894-1692_"
  class="css-4rbku5 css-901oao css-cens5h r-1ghhsy9 r-1loqt21 r-gg6oyi r-ubezar r-majxgm r-135wba7 r-ymttw5"
  style="-webkit-line-clamp: 2;"
>
  Blog
</a>
```

**Comment by div3xi** [comment]
@LukasMurdock we are currently re-making our documentation, it will be fixed then. Thank you for the issue.
