### ISSUE TITLE
Bad texts are showing on `README.md` 🐞

### ISSUE THREAD

**Issue by sarkartanmay393** [anytypeio/docs#16]
#### Link
> `README.md`

#### Description
> As I attached the screenshot, there are lot of bad text with referring to other pages.

![Screenshot_20221011-141952.png](https://user-images.githubusercontent.com/84321236/195044573-dfac2e45-3192-4648-a097-fab0e52fe7f1.png)

**If it seems a genuine issue, I would very much happy to contribute to it.**

**Comment by SamBouwer** [comment]
@sarkartanmay393 I believe this is the case because the docs are not to be read on GitHub, but rather to  be consumed via https://doc.anytype.io, where the texts are properly rendered.

**Comment by sarkartanmay393** [comment]
Oh yes, I see.
